# Generated by Django 5.0 on 2025-12-11 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='data',
            new_name='company_details',
        ),
    ]
