# Generated by Django 5.0 on 2025-12-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0002_rename_data_company_company_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('Small Business', 'Small Business'), ('Startup', 'Startup'), ('Corporate', 'Corporate')], max_length=50),
        ),
    ]
